export enum VariableComponentEnum {
  TITRE_GAUCHE = 'TITRE_GAUCHE',
  TITRE_DROIT = 'TITRE_DROIT',
  PARAGRAPHE_GAUCHE = 'PARAGRAPHE_GAUCHE',
  PARAGRAPHE_DROIT = 'PARAGRAPHE_DROIT',
  TITRE_INSCRIPTION = 'TITRE_INSCRIPTION',
  PARAGRAPHE_INSCRIPTION = 'PARAGRAPHE_INSCRIPTION',
}
